### ISSUE TITLE
ESM/CJS issues in 0.3.0 and above

### ISSUE THREAD

**Issue by joshkel** [curvenote/prosemirror-docx#51]
After upgrading from 0.2.1 to 0.3.0 or above, I started getting the following error in my CJS project:

```
file:///Users/josh/tmp/node_modules/prosemirror-docx/dist/cjs/index.js:2
Object.defineProperty(exports, "__esModule", { value: true });
                      ^

ReferenceError: exports is not defined
```

In an ESM project, I instead get this error:

```
file:///Users/josh/tmp/node_modules/prosemirror-docx/dist/cjs/index.js:2
Object.defineProperty(exports, "__esModule", { value: true });
                      ^

ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/Users/josh/tmp/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///Users/josh/tmp/node_modules/prosemirror-docx/dist/cjs/index.js:2:23
    at ModuleJob.run (node:internal/modules/esm/module_job:271:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:547:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)
```

If I understand correctly, it's a mistake for prosemirror-docx's package.json to advertise itself as a module (`"type": "module"`) while listing the `main` as a CJS `.js` file. (The `"module": "dist/esm/index.js"` entry in prosemirror-docx's package.json has no effect in Node.js; see https://stackoverflow.com/a/42817320/25507.)

**Comment by jdjoshuadavison** [comment]
I'm also encountering these errors when trying to build a Node project that uses `prosemirror-docx` version 0.3.0 or above. It continues to build successfully in my client side (Vue 3) project.

It seems the addition of `"type": "module"` in `package.json` is the culprit.

Removing that line allows me to successfully build a Node project - either using CommonJS or using `createRequire` in an ESM project.

This change was introduced in PR #35. Notably, the CI check on that PR is failing at the `yarn run test` step with the error: `ReferenceError: module is not defined`.

**Comment by PratikAwaik** [comment]
encountering this issue as well. please fix it

**Comment by condorheroblog** [comment]
@dan-cooke Hi,

I want to solve this problem, but I have two questions

1. Do you want us to release pure ESM specification packages (many underlying libraries do this now)

2. To release a package compatible with CJS and ESM, what packaging tool do you want to use (tsup, unbuild, vite, rolldown, etc.)

**Comment by dan-cooke** [comment]
Thanks @condorheroblog  this should be fixed now in 0.6.0 #56

**Comment by joshkel** [comment]
Please re-open this issue. I'm still seeing the same error in 0.6.0:

```
ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/app/node_modules/prosemirror-docx/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///app/node_modules/prosemirror-docx/dist/cjs/index.js:2:23
    at ModuleJobSync.runSync (node:internal/modules/esm/module_job:436:37)
    at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:427:47)
    at loadESMFromCJS (node:internal/modules/cjs/loader:1561:24)
    at Module._compile (node:internal/modules/cjs/loader:1712:5)
    at Object..js (node:internal/modules/cjs/loader:1895:10)
    at Module.load (node:internal/modules/cjs/loader:1465:32)
    at Function._load (node:internal/modules/cjs/loader:1282:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
```

I believe it's the same root problem as I described above: If I understand correctly, it's a mistake for prosemirror-docx's package.json to advertise itself as a module ("type": "module") while listing the main as a CJS .js file. (The "module": "dist/esm/index.js" entry in prosemirror-docx's package.json has no effect in Node.js; see https://stackoverflow.com/a/42817320/25507.)

[are-the-types-wrong](https://arethetypeswrong.github.io/?p=prosemirror-docx%400.6.0) is throwing several errors for prosemirror-docx 0.6.0, which likely reflects this problem.

I think that 9516405aac3c6afbd0c5b1d51072cf9e04feed76 was more correct; are-the-types-wrong doesn't complain about it, and, based on a brief test in my CJS Node.js application, it seems to work. (I haven't tested in an ESM Node.js application.)

**Comment by dan-cooke** [comment]
Re-opened @joshkel  apologies, but I really don't have time to look into this at the moment, we exclusively use this library in the browser.

@condorheroblog  are you able to have a look if you get any time?

Much appreciated

**Comment by condorheroblog** [comment]
I have solved this problem in [56](https://github.com/curvenote/prosemirror-docx/pull/56). But the code has not been released.

---

Pease check my comment, the generated test file is incorrect.

https://github.com/curvenote/prosemirror-docx/pull/56#issuecomment-3017579221

---

I will submit PR again.

**Comment by dan-cooke** [comment]
@condorheroblog apologies I didn’t get a notification for that - think because it was merged 

Can you reopen it again? And ensure there is a change set 

Thank you!

**Comment by joshkel** [comment]
> Can you reopen it again? And ensure there is a change set

Looks like the PR has been reopened as #61.
